# Generated by Django 3.1.7 on 2021-03-11 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighboor', '0002_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='body',
            new_name='catagory',
        ),
        migrations.AddField(
            model_name='ticket',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ticket',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='neighboor.person'),
        ),
    ]
