# Generated by Django 3.1 on 2021-03-12 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neighboor', '0003_auto_20210311_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='catagory',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='person',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
