# Generated by Django 3.1 on 2021-03-12 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neighboor', '0007_auto_20210311_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='helpee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='helper',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='helper', to=settings.AUTH_USER_MODEL),
        ),
    ]
