# Generated by Django 3.1 on 2021-03-12 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neighboor', '0008_auto_20210311_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='items',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ticket',
            name='need_by',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='helper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='helper', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
